name: Build wheels

on: [push, workflow_dispatch, workflow_call]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        run: pip wheel ./CompilerInterface -w ./CompilerInterface/dist
        # uses: pypa/cibuildwheel@v2.13.1
        # with:
        #   package-dir: CompilerInterface
        env:
          # CIBW_SKIP: "pp* *-musllinux_*"
          CIBW_ARCHS: "x86_64"
          # CIBW_MANYLINUX_X86_64_IMAGE: "ghcr.io/iith-compilers/manylinux2014-llvm/manylinux2014-llvm:x86-llvm17"
          # CIBW_BEFORE_ALL: "bash Manylinux2014_Compliant_Source/pkg/build.sh"
          # CIBW_TEST_REQUIRES: pytest
          # CIBW_TEST_COMMAND: "pytest {project}/Manylinux2014_Compliant_Source/pkg/tests"

      - uses: actions/upload-artifact@v3
        with:
          path: ./CompilerInterface/dist/*.whl

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions